spring.application.name=inventory-service

spring.kafka.producer.bootstrap-servers=localhost:9902
spring.kafka.producer.transaction-id-prefix=inventory-transaction-service-${random.value}-

spring.kafka.consumer.group-id=inventory-consumer-group


kafka.topic.order-events=order.events.v1
kafka.topic.inventory-events=inventory.events.v1

#DB
spring.datasource.url=jdbc:mysql://localhost:3306/invservice
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=create-drop

